### ISSUE TITLE
feat(chain): Extend ChainConfig to be TOML-configurable

### ISSUE THREAD

**Issue by refcell** [a16z/magi#38]
### Overview

Extend the [ChainConfig](https://github.com/a16z/magi/blob/master/src/config/mod.rs#L106) to be configurable via the `magi.toml` in `~/.magi/magi.toml`.

**Comment by ncitron** [comment]
Sounds good! I'd just make sure to test this one out a bit when your working on it, since it is easy to make a mistake on deserializing some of the fields.

**Comment by merklefruit** [comment]
Happy to take this then :)

**Comment by ncitron** [comment]
Sounds good!

**Comment by merklefruit** [comment]
It looks like the `chain` table can already be configured via TOML, with the following notation:

```toml
[default]
l1_rpc_url = "https://example1.com"
l2_rpc_url = "https://example2.com"
l2_engine_url = "https://example3.com"
jwt_secret = "saiudhfiopwgjpwa"
checkpoint_sync_url = "https://example4.com"
rpc_port = 9591

[default.chain]
network = "optimism-goerli-test-toml"
system_config_contract ="0x00851f927Ee40dE99aaBb7461C00f9622ab91d60"
batch_inbox = "0xffff000000000000000000000000000000000420"
deposit_contract = "0x5b47E1A08Ea6d985D6649300584e6722Ec4B1383"
l2_to_l1_message_passer = "0xEF2ec5A5465f075E010BE70966a8667c94BCe15a"
max_channel_size = 100_000_000
channel_timeout = 300
seq_window_size = 3600
max_seq_drift = 600
regolith_time = 1679079600
blocktime = 20

[default.chain.l1_start_epoch]
hash = "0xbeef1bf3754c01f6bb9fe057c1578b87a8571ce2e9be5ca14bace6eccfd336c7"
number = 8300214
timestamp = 1673550516

[default.chain.l2_genesis]
hash = "0xbeef3549ea4313b784eadd9b8e8a69913b368b7366363ea814d7707ac505175f"
number = 4061224
parent_hash = "0xdead7a44f1422f4cab59b076548c075e79bd59e691a23fbce027f572a2a49dc9"
timestamp = 1673550516

[default.chain.system_config]
batch_sender = "0xaaaaaaaaa26b69bfc676c0013e12a1a11411eec9"
gas_limit = "0x17D7842"
l1_fee_overhead = "0x836"
l1_fee_scalar = "0xF4240"
```
